name: Android NDK Build and Push

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # 确保获取完整的 Git 历史记录

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Download and set up NDK
      run: |
        wget -q https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
        sudo unzip -q android-ndk-r21e-linux-x86_64.zip -d /opt
        echo "ANDROID_NDK_HOME=/opt/android-ndk-r21e" >> $GITHUB_ENV
        echo "$ANDROID_NDK_HOME" >> $GITHUB_PATH

    - name: Build with NDK
      run: |
        /opt/android-ndk-r21e/ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=Android.mk NDK_APPLICATION_MK=Application.mk

    - name: Copy Compiled Files
      run: |
        mkdir -p build_output
        cp -r ./libs/* build_output/

    - name: Commit and Push
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions@github.com'
        git add build_output/*
        git commit -m "Automatically push compiled files"
        git push
