name: Encrypt and Upload Files

on:
  push:
    branches:
      - main  # 或者你希望触发此工作流的任何分支

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 最新版本作为运行环境

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # 检出你的仓库代码

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # 安卓 13 开发通常需要 JDK 11
        distribution: 'adopt'

    - name: Install Android SDK
      run: |
       wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
       unzip commandlinetools-linux-7583922_latest.zip -d android-sdk
       echo "ANDROID_HOME=$PWD/android-sdk" >> $GITHUB_ENV
       echo "$PWD/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
       yes | $PWD/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
       $PWD/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33"


    - name: Install SHC
      run: |
        sudo apt-get update
        sudo apt-get install -y shc

    - name: Encrypt Files
      run: |
        shc -f demo.sh -o demo1.sh  # 将你的脚本文件加密
        # 你可以添加更多命令来加密其他需要的文件

    - name: Commit and Push Encrypted Files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add encrypted-script  # 添加加密后的文件
        git commit -m "Add encrypted files"
        git push
