name: Encrypt and Upload Files

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install Android SDK
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
        unzip commandlinetools-linux-7583922_latest.zip -d android-sdk-temp
        mkdir -p $GITHUB_WORKSPACE/android-sdk/cmdline-tools
        mv android-sdk-temp/cmdline-tools $GITHUB_WORKSPACE/android-sdk/cmdline-tools/latest
        echo "ANDROID_HOME=$GITHUB_WORKSPACE/android-sdk" >> $GITHUB_ENV
        echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33"

    - name: Install SHC
      run: |
        sudo apt-get update
        sudo apt-get install -y shc

    - name: Encrypt Files
      run: |
        shc -f demo.sh -o demo1.sh

    - name: Commit and Push Encrypted Files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add demo1.sh
        git commit -m "Add encrypted files"
        git push
