name: Android NDK Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Download and set up NDK
      run: |
        wget -q https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
        sudo unzip -q android-ndk-r21e-linux-x86_64.zip -d /opt
        echo "ANDROID_NDK_HOME=/opt/android-ndk-r21e" >> $GITHUB_ENV
        echo "$ANDROID_NDK_HOME" >> $GITHUB_PATH

    - name: Build with NDK
      run: |
        /opt/android-ndk-r21e/ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=Android.mk NDK_APPLICATION_MK=Application.mk

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Compiled-Program
        path: ./libs
